name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  backend-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml
          tools: composer, phpcs

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Check PHP coding style with PHPCS
        run: ./vendor/bin/phpcs --standard=./ruleset.xml ./app

